# Data processing configuration
data_cleaning:
  input_path: data/raw/bike_sharing_modified.csv
  original_path: data/raw/bike_sharing_original.csv
  output_path: data/processed/bike_sharing_cleaned.csv

feature_engineering:
  input_path: data/processed/bike_sharing_cleaned.csv
  output_path: data/processed/bike_sharing_transformed.csv

# Training configuration
train:
  input_path: data/processed/bike_sharing_transformed.csv
  test_size: 0.2
  random_state: 42

# MLflow configuration
mlflow:
  experiment_name: Bike_Sharing_DVC_Pipeline

# Model configurations
models:
  random_forest:
    model_class: RandomForestRegressor
    configs:
      - n_estimators: 100
        max_depth: 10
        random_state: 42
        n_jobs: -1

      - n_estimators: 200
        max_depth: 20
        random_state: 42
        n_jobs: -1

      - n_estimators: 300
        max_depth: 15
        min_samples_leaf: 2
        random_state: 42
        n_jobs: -1

      - n_estimators: 500
        max_depth: 15
        random_state: 42
        n_jobs: -1

      - n_estimators: 500
        max_depth: 25
        min_samples_leaf: 1
        random_state: 42
        n_jobs: -1

      - n_estimators: 300
        max_depth: 18
        min_samples_leaf: 2
        min_samples_split: 5
        random_state: 42
        n_jobs: -1

  elastic_net:
    model_class: ElasticNet
    configs:
      - alpha: 0.1
        l1_ratio: 0.5
        random_state: 42
        max_iter: 10000

      - alpha: 0.001
        l1_ratio: 0.8
        random_state: 42
        max_iter: 10000

      - alpha: 0.1
        l1_ratio: 0.6
        random_state: 42
        max_iter: 10000

      - alpha: 0.005
        l1_ratio: 0.9
        random_state: 42
        max_iter: 10000

  svr:
    model_class: SVR
    configs:
      - kernel: rbf
        C: 10
        epsilon: 0.1

      - kernel: rbf
        C: 1
        epsilon: 0.05

  xgboost:
    model_class: XGBRegressor
    configs:
      - n_estimators: 150
        max_depth: 5
        random_state: 42
        learning_rate: 0.1

      - n_estimators: 300
        max_depth: 7
        random_state: 42
        learning_rate: 0.05

      - n_estimators: 400
        max_depth: 6
        random_state: 42
        learning_rate: 0.03

      - n_estimators: 500
        max_depth: 5
        random_state: 42
        learning_rate: 0.05

  lightgbm:
    model_class: LGBMRegressor
    configs:
      - n_estimators: 150
        max_depth: 10
        random_state: 42
        learning_rate: 0.1
        n_jobs: -1

      - n_estimators: 300
        max_depth: 15
        random_state: 42
        learning_rate: 0.05
        n_jobs: -1

      - n_estimators: 400
        max_depth: 12
        random_state: 42
        learning_rate: 0.03
        n_jobs: -1

      - n_estimators: 600
        max_depth: 15
        random_state: 42
        learning_rate: 0.05
        n_jobs: -1
